public enum TYPE {

  LITERAL_ATOM,
  NUMERIC_ATOM,
  OPEN_PARENTHESIS,
  CLOSING_PARENTHESIS,
  LITERAL_OPEN_PARENTHESIS,
  LITERAL_CLOSING_PARENTHESIS,
  NUMERIC_OPEN_PARENTHESIS,
  NUMERIC_CLOSING_PARENTHESIS,
  INVALID_PREFIX,
  EOF,
  ERROR
}
